# Generated by Django 5.2.3 on 2025-09-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_proof',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('qr', 'QR Code'), ('upi', 'UPI Direct'), ('gpay', 'Google Pay'), ('phonepe', 'PhonePe'), ('paytm', 'Paytm')], max_length=20),
        ),
    ]
