# Generated by Django 5.2.3 on 2025-09-23 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_facilitysport_max_players'),
        ('sport_teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField()),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_challenges', to='sport_teams.team')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_invitations', to='sport_teams.team')),
                ('preferred_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_requests', to='facilities.facility')),
                ('preferred_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_requests', to='facilities.timeslot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
