# Generated by Django 5.2.3 on 2025-09-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_sporttype_timeslot_alter_facility_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TurfZone', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('about_us', models.TextField()),
                ('booking_time_limit', models.IntegerField(default=15)),
                ('cancellation_time_limit', models.IntegerField(default=24)),
                ('max_advance_booking_days', models.IntegerField(default=30)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('terms_conditions', models.TextField(blank=True)),
                ('privacy_policy', models.TextField(blank=True)),
                ('social_links', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='facility',
            name='closing_time',
            field=models.TimeField(default='23:00'),
        ),
        migrations.AddField(
            model_name='facility',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='opening_time',
            field=models.TimeField(default='06:00'),
        ),
        migrations.AddField(
            model_name='facility',
            name='rules',
            field=models.TextField(blank=True),
        ),
    ]
