# Generated by Django 5.2.3 on 2025-09-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_sitesettings_facility_amenities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='longitude',
        ),
        migrations.AddField(
            model_name='facility',
            name='google_maps_link',
            field=models.URLField(blank=True, help_text='Enter the Google Maps link for the facility location', max_length=500, null=True),
        ),
    ]
