# Generated by Django 5.2.3 on 2025-09-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_remove_facility_latitude_remove_facility_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitysport',
            name='max_players',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
