# Generated by Django 5.2.3 on 2025-09-19 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_sport', models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football')], max_length=20)),
                ('playing_side', models.CharField(choices=[('right', 'Right Handed'), ('left', 'Left Handed')], max_length=10)),
                ('is_wicketkeeper', models.BooleanField(default=False)),
                ('batting_style', models.CharField(blank=True, choices=[('opening', 'Opening Batsman'), ('top_order', 'Top Order Batsman'), ('middle_order', 'Middle Order Batsman'), ('finisher', 'Finisher'), ('all_rounder', 'All-Rounder')], max_length=20, null=True)),
                ('bowling_style', models.CharField(blank=True, choices=[('fast', 'Fast Bowler'), ('medium_fast', 'Medium Fast'), ('off_break', 'Off Break'), ('leg_break', 'Leg Break')], max_length=20, null=True)),
                ('football_position', models.CharField(blank=True, choices=[('goalkeeper', 'Goalkeeper'), ('defender', 'Defender'), ('midfielder', 'Midfielder'), ('forward', 'Forward')], max_length=20, null=True)),
                ('football_style', models.CharField(blank=True, choices=[('striker', 'Striker'), ('winger', 'Winger'), ('attacking_mid', 'Attacking Midfielder'), ('defensive_mid', 'Defensive Midfielder'), ('center_back', 'Center Back'), ('full_back', 'Full Back'), ('sweeper', 'Sweeper')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
