# Generated by Django 5.2.3 on 2025-09-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_migrate_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
