# Generated by Django 5.2.3 on 2025-09-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_remove_booking_booking_type_and_more'),
        ('facilities', '0003_sitesettings_facility_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('expired', 'Expired')], default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('facility_sport', 'date', 'time_slot')},
        ),
    ]
