# Generated by Django 5.2.3 on 2025-09-15 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_base_price_booking_discount_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
